spring:
  jpa:
    #show-sql: true
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:3306/lagunachicken?serverTimezone=UTC&autoReconnect=true&useSSL=false
    username: root
    password: Lagun@Chicken97$ #password en servidor de unraid
server:
  port: 8080
  ssl:
    enabled: false
    #key-store: classpath:keystore.p12
    #key-store-password: 123456
    #key-store-type: PKCS12
    #key-alias: tomcat
serlo:
  app:
    jwtCookieName: bezkoder
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000
    fileDirectory: ../files/
    emailRemitente: sernagustavo3@gmail.com
    passwordRemitente: Paachanga4$
    emailDestinatario: sernagustavo3@gmail.com