spring:
  jpa:
    #show-sql: true
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:3306/lagunachicken?serverTimezone=UTC&autoReconnect=true&useSSL=false
    username: root
    password: laguchicken1
serlo:
  app:
    jwtCookieName: bezkoder
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000
    fileDirectory: C:\Users\Administrador\Documents\lagunachicken-flotillas\files
    emailRemitente: sernagustavo3@gmail.com
    passwordRemitente: Paachanga4$
    emailDestinatario: sernagustavo3@gmail.com