spring:
  jpa:
    #show-sql: true
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:192.168.2.115}:3306/lagunachicken?serverTimezone=UTC&autoReconnect=true&useSSL=false
    username: root
    password:
server:
  port: 9705
serlo:
  app:
    jwtCookieName: bezkoder
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000
    fileDirectory: ../files/
    emailRemitente: sernagustavo3@gmail.com
    passwordRemitente: Paachanga4$
    emailDestinatario: sernagustavo3@gmail.com