spring:
  jpa:
    #show-sql: true
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:3306/lagunachicken?serverTimezone=UTC&autoReconnect=true&useSSL=false
    username: root
    password: gustavo789
serlo:
  app:
    jwtCookieName: bezkoder
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000
    fileDirectory: /Users/gustavoserna/work/lagunachicken-full/files/